### ISSUE TITLE
Could you please share which database the repertory had used?

### ISSUE THREAD

**Issue by Jasonsey** [aditya9211/Blur-and-Clear-Classification#6]
Dear 
I am working on distinguishing blurred images problem. And I think this repertory is interesting and it must be helpful for my work. But I have not yet seen the database used.  Could you please tell me which database the repertory had used?

Appreciate your help.

Thanks and regards.
--
Jasonsey

**Comment by Jasonsey** [comment]
Hi Aditya
Thank you for your answer. Maybe I can label some pics myself. And Could you please tell me what the standard used to label bad pics and good pics is. 
For bad pics, the more blurred pic is better or the clear pic but with little blur is better. And to good pics, the same question. 
I'm new to prepare such database. And Though it is a small hint, it is also important for my work.

Appreciate your help.

Thank you again.

Jasonsey

**Comment by aditya9211** [comment]
Hi Jasonsey,
For mine task of labeling, I used the variance of Laplacian of Gaussian filter as an approximate technique to label the images, which helps to tag data faster.
You can search for it LoG filter.

Aditya

**Comment by Jasonsey** [comment]
Hi Aditya
It's very helpful to separate blurred pics from clear pics. But I have encountered a new problem. I have a database that contains many clear pictures, but fuzzy pictures are few. And My deep learning  algorithm needs a lot of fuzzy pictures. So I want to create fuzzy pictures myself. Have you tried to generate blurred blurred pics from blurred pics? 

Appreciate your help.

Thanks and regards.

Jasonsey

**Comment by aditya9211** [comment]
Hi,

Have seen one repo but doesn't remember now. For the blur part, you can
pick a patch in an image
and apply Wavelet Transform, blur filter to it smartly

You can refer this https://github.com/Sibozhu/MotionBlur-detection-by-CNN



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
15/09/18,
13:58:36

**Comment by aditya9211** [comment]
Closing this issue as no updates got
