### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by DecentMakeover** [aditya9211/Blur-and-Clear-Classification#9]
Hi thanks for sharing your work.

but i get this error when running train.py

    Train Data Path Success .....
    Train Label Path Success .....  
    Test Data Path Success .....
    Test Label Path Success .....

    Saving the splitting results......

    Traceback (most recent call last):
     File "train.py", line 564, in <module>
      main()
     File "train.py", line 532, in main
     train_images = np.insert(train_images, 0, 1, axis=1) 
     File "/home/jeniffer/.local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4431, in   insert
    new = empty(newshape, arr.dtype, arrorder)
      MemoryError`

Any ideas?

**Comment by aditya9211** [comment]
Maybe your data size may be too big to fit in the memory after adding bias term in the big input array.
Or check the data type of _train_images_
Maybe this can help you https://github.com/numpy/numpy/issues/9960

**Comment by aditya9211** [comment]
Closing issue due to no further activity for a long time.
In case it doesn't resolve, kindly state the error.
